### ISSUE TITLE
Error using speechmarktype::Viseme

### ISSUE THREAD

**Issue by nibl** [ahmadmayahi/php-amazon-polly#13]
Using Speechmarktype::Viseme results in a fatal error. Word and Sentence work as expected. Can anyone else reproduce this error?

**Comment by ahmadmayahi** [comment]
Hi @nibl 

Can you please share the error message that you're getting?

**Comment by nibl** [comment]
@ahmadmayahi Below is the output. The line of code is `->withSpeechMarks(SpeechMarkType::Viseme) `. 

PHP Warning:  Undefined property: stdClass::$start in /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Support/GenerateSpeechMarks.php on line 48
PHP Warning:  Undefined property: stdClass::$end in /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Support/GenerateSpeechMarks.php on line 49
PHP Fatal error:  Uncaught TypeError: AhmadMayahi\Polly\Data\SpeechMark::__construct(): Argument #3 ($start) must be of type int, null given, called in /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Support/GenerateSpeechMarks.php on line 50 and defined in /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Data/SpeechMark.php:11
Stack trace:
#0 /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Support/GenerateSpeechMarks.php(50): AhmadMayahi\Polly\Data\SpeechMark->__construct()
#1 [internal function]: AhmadMayahi\Polly\Support\GenerateSpeechMarks->AhmadMayahi\Polly\Support\{closure}()
#2 /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Support/GenerateSpeechMarks.php(36): array_map()
#3 /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Polly.php(171): AhmadMayahi\Polly\Support\GenerateSpeechMarks->generate()
#4 /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Polly.php(122): AhmadMayahi\Polly\Polly->generateSpeechMarks()
#5 /home/nibl/p1.php(44): AhmadMayahi\Polly\Polly->convert()
#6 {main}
thrown in /home/nibl/vendor/ahmadmayahi/php-amazon-polly/src/Data/SpeechMark.php on line 11

**Comment by ahmadmayahi** [comment]
@nibl Fixed.
Please update to the latest version v1.2.0
